#!/system/bin/sh

if [ -f /.bootstamp ]; then
  exit 0
fi

mount -o remount,rw rootfs /
killall bootanimation
# mount /data now to get recovery mode detection working
mount -t ext4 /dev/block/bootdevice/by-name/userdata /data -o nosuid,nodev,barrier=1,noauto_da_alloc

# Define log filename
LOG="/data/temp/2nd-init_"$(date +%F_%T)".log"

# touch 2nd-init log file
touch "$LOG"
echo "2nd-init boot log" >> "$LOG"
date >> "$LOG"

# touch stamp to prevent loop execution
touch /.bootstamp

#
# check mode
#
TYPE=normal
if [ -f /data/temp/.recovery_mode ]; then
  TYPE=recovery
  echo "Recovery mode - file" >> "$LOG"
else
  key=
  if [ -e /system/bootstrap/getkey ]; then
    key=$(/system/bootstrap/getkey)
  fi
  if [ "$key" = 115 ]; then
    TYPE=recovery
    echo "Recovery mode - getkey" >> "$LOG"
  else
    echo "Normal boot mode" >> "$LOG"
  fi
fi
echo "ls -laZ /" >> "$LOG"
ls -laZ / >> "$LOG"
echo "" >> "$LOG"
# remove recoverymode trigger and unmount data again
rm /data/temp/.recovery_mode
umount /data

# Continue init process
kill -CONT 1
echo "kill -CONT 1" >> "$LOG"
date >> "$LOG"
echo "ps -Z" >> "$LOG"
ps -Z >> "$LOG"
echo "" >> "$LOG"
  
# no boot.tar - stock rom
if [ "$TYPE" = "normal" ] && [ ! -f /system/bootstrap/boot.tar ] ; then
  echo "Stock ROM detected, exiting 2nd-init" >> "$LOG"
  date >> "$LOG"
  exit 0
fi

# remove symbolic links
rm sdcard

#
# remove lg crap
#
rm /*.rc
rm /*.sh
echo "Removed /*.rc and /*.sh" >> "$LOG"
date >> "$LOG"
echo "ls -laZ /" >> "$LOG"
ls -laZ / >> "$LOG"
echo "ps -Z" >> "$LOG"
ps -Z >> "$LOG"

#
# volume down - recovery mode
#
if [ "$TYPE" = "recovery" ]; then
  # unlink /etc
  rm /etc
  mkdir /etc

  cp -fr /system/bootstrap/recovery.tar /
  tar xf /recovery.tar
  echo "Extracted recovery.tar" >> "$LOG"
  date >> "$LOG"
  echo "ls -laZ /" >> "$LOG"
  ls -laZ / >> "$LOG"
  echo "ps -Z" >> "$LOG"
  ps -Z >> "$LOG"
  if [ ! -z "$restart_adb" ]; then
    killall adbd
  fi
  killall ueventd
  
  mkdir /tmp
  mkdir /cache
  mkdir /sdcard
  chmod 666 /dev/graphics/fb*

  mount -o remount,rw /system /system
#
# normal mode
#
else
  cp -fr /system/bootstrap/boot.tar /
  tar xf /boot.tar
  echo "Extracted boot.tar" >> "$LOG"
  date >> "$LOG"
  echo "ls -laZ /" >> "$LOG"
  ls -laZ / >> "$LOG"
  killall ueventd
  echo "ps -Z" >> "$LOG"
  ps -Z >> "$LOG"
fi

# unmount stuff
umount /dev/cpuctl
umount /dev/pts
umount /data
umount /dvp
umount /persist
umount /sys/kernel/debug
umount /system/app
umount /mpt
umount /mnt/asec
umount /mnt/obb
umount /mnt/extasec
umount /mnt/extobb

echo "umount all the things." >> "$LOG"
date >> "$LOG"
echo "ls -laZ /" >> "$LOG"
ls -laZ / >> "$LOG"
# set our init only to the first core << check this
#/system/bootstrap/taskset -p -c 0 1
#/system/bootstrap/taskset -c 0 /system/bootstrap/2nd-init
#/system/bootstrap/2nd-init
/init

echo "run /init" >> "$LOG"
echo "ps -Z" >> "$LOG"
ps -Z >> "$LOG"
echo "exit" >> "$LOG"
date >> "$LOG"
exit 0
